---
title: "Rshiny Homework 2"
author: "Devraj Kori"
date: "10/3/2019"
output: html_document
---


```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE)
library(rmarkdown)
library(knitr)
library(dplyr)
library(tidyr)
library(ggplot2)
require(readxl)
require(openxlsx)
require(reshape2)
require(scales)
require(gridExtra)
library(tidycensus)
#for QWI
library(httr)
library(jsonlite)
library(readr)
library(leaflet)
library(sf)
library(rgdal)
```

```{r load_variables}
#load the available variables from acs 2017, to find an interesting one
v17<-load_variables(2017,"acs5", cache=TRUE)

```

```{r load_geo_files}
#pull median household income at the tract level from ACS as polygons
alle_income<-get_acs(variables=c(Median_hh_income="B06011_001"),
                     state="PA",
                     county="Allegheny",
                     geography="tract",
                     year=2017,
                     geometry=TRUE)%>%
  

#list.files()
#read in cell tower points
cell_towers<-readOGR('Allegheny_County_Cell_Tower_Points.geojson')
#read in snow route centerlines
snow_routes<-readOGR('Allegheny_County_Snow_Route_Centerlines_20162017.geojson')

```

```{r create_map}
#create icons object for points
icons <- awesomeIconList(
  Towers = makeAwesomeIcon(icon = "fa-signal", library = "fa", markerColor = "blue")
  )
#create palette for polygons
pal <- colorNumeric(palette = "RdYlGn", domain = alle_income$estimate, n = nrow(alle_income))

#transform alle_income projection
alle_income_map<-alle_income%>%
  st_transform(crs = "+init=epsg:4326")
#create map with all 3 layers, layer selector, basemap selector
leaflet()%>%
  addProviderTiles(provider = "CartoDB.Positron", group = "Positron")%>%
  addProviderTiles(provider = "OpenStreetMap.Mapnik", group = "OSM")%>%
  #add cell tower points to map
  addAwesomeMarkers(data=cell_towers,icon=icons["Towers"],
                    #set group name
                    group="Cell Towers")%>%
  #add median income polygons
  addPolygons(data=alle_income_map,
              #remove borderlines
              stroke=FALSE,
              #set color palette
              color=~pal(estimate),
              #set opacity
              fillOpacity=.5,
              #set group name
              group="Median Income")%>%
  #add legend
  addLegend(data=alle_income_map,"bottomright",
            #set palette
            pal=pal,
            #indicate values
            values=~estimate,
            title="Median HH Income")%>%
  #add snow routes
  addPolylines(data=snow_routes,group="snow routes")%>%
  addLayersControl(
    baseGroups = c("Positron","OSM"),
    overlayGroups = c("Cell Towers", "Median Income","Snow Routes"),
    options = layersControlOptions(collapsed = FALSE))
  

```